In [23]:
import csv
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.naive_bayes import GaussianNB
from sklearn import linear_model
from sklearn.cross_validation import KFold
from sklearn.metrics import f1_score
import numpy as np

In [24]:
with open("J.csv", 'rb') as csvfile:
    reader = csv.DictReader(csvfile)
    features = []
    labels = []
    for row in reader:
        feature = []
        feature.append(float(row['name']))
        feature.append(float(row['addr']))
        feature.append(float(row['post']))
        feature.append(float(row['phone']))
        features.append(feature)
        labels.append(int(row['label']))

In [25]:
X = np.array(features)
y = np.array(labels)
kf = KFold(250, n_folds=10)
t_same = 0
svm_same = 0
rf_same = 0
nb_same = 0
lr_same = 0
for train_index, test_index in kf:
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    # http://scikit-learn.org/stable/modules/tree.html#tree
    t_clf = tree.DecisionTreeClassifier()
    t_clf = t_clf.fit(X_train, y_train)
    t_y_predict = t_clf.predict(X_test)
    t_same += f1_score(y_test, t_y_predict)
#     for i in xrange(25):
#         if t_y_predict[i] == y_test[i]:
#             t_same += 1
    
    # http://scikit-learn.org/stable/modules/svm.html#svm
    svm_clf = svm.SVC()
    svm_clf = svm_clf.fit(X_train, y_train)
    svm_y_predict = svm_clf.predict(X_test)
    svm_same += f1_score(y_test, svm_y_predict)
#     for i in xrange(25):
#         if svm_y_predict[i] == y_test[i]:
#             svm_same += 1
    
    # http://scikit-learn.org/stable/modules/generated/
    # sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier
    rf_clf = RandomForestClassifier(n_estimators=10, max_depth=3)
    rf_clf = rf_clf.fit(X_train, y_train)
    rf_y_predict = rf_clf.predict(X_test)
    rf_same += f1_score(y_test, rf_y_predict)
#     for i in xrange(25):
#         if rf_y_predict[i] == y_test[i]:
#             rf_same += 1
    
    # http://scikit-learn.org/stable/modules/naive_bayes.html#naive-bayes
    gnb = GaussianNB()
    nb_y_predict = gnb.fit(X_train, y_train).predict(X_test)
    nb_same += f1_score(y_test, nb_y_predict)
#     for i in xrange(25):
#         if nb_y_predict[i] == y_test[i]:
#             nb_same += 1
    
    # http://scikit-learn.org/stable/modules/generated/
    # sklearn.linear_model.LogisticRegression.html#sklearn.linear_model.LogisticRegression
    
    # http://scikit-learn.org/stable/modules/generated/
    # sklearn.linear_model.SGDClassifier.html#sklearn.linear_model.SGDClassifier
    lr_clf = linear_model.SGDClassifier(loss='log')
    lr_clf = lr_clf.fit(X_train, y_train)
    lr_y_predict = lr_clf.predict(X_test)
    lr_same += f1_score(y_test, lr_y_predict)
#     for i in xrange(25):
#         if lr_y_predict[i] == y_test[i]:
#             lr_same += 1
            
# t_acc = t_same / (float)(250)
# svm_acc = svm_same / (float)(250)
# rf_acc = rf_same / (float)(250)
# nb_acc = nb_same / (float)(250)
# lr_acc = lr_same / (float)(250)

print t_acc/5
print svm_acc/5
print rf_acc/5
print nb_acc/5
print lr_acc/5

/u/l/i/liliu/codelib/anaconda2/lib/python2.7/site-packages/sklearn/metrics/classification.py:1076: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true samples.
  'recall', 'true', average, warn_for)


0.1824
0.1864
0.188
0.1864
0.1848


In [28]:
for train_index, test_index in kf:
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    # http://scikit-learn.org/stable/modules/tree.html#tree
    t_clf = tree.DecisionTreeClassifier()
    t_clf = t_clf.fit(X_train, y_train)
    t_y_predict = t_clf.predict(X_test)
    t_same += f1_score(y_test, t_y_predict)
    print t_y_predict

[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[-1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1]
[-1 -1 -1  1  1  1 -1 -1 -1 -1 -1  1 -1  1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1 -1]
[-1 -1 -1  1 -1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  1  1  1  1 -1 -1  1  1  1]
[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 -1  1]
[ 1  1  1  1  1  1  1  1 -1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[ 1 -1  1  1  1  1  1 -1  1  1  1  1  1  1  1  1  1  1  1  1  1 -1  1 -1  1]
[-1  1  1 -1  1  1  1  1  1 -1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
